/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './route/__root'
import { Route as IndexImport } from './route/index'
import { Route as CheckoutIndexImport } from './route/checkout/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CheckoutIndexRoute = CheckoutIndexImport.update({
  path: '/checkout/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutIndexRoute
}

interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutIndexRoute
}

interface FileRoutesById {
  '/': typeof IndexRoute
  '/checkout/': typeof CheckoutIndexRoute
}

interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/checkout'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/checkout'
  id: '/' | '/checkout/'
  fileRoutesById: FileRoutesById
}

interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/checkout/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/checkout/": {
      "filePath": "checkout/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
